const PROJECTS = [
  {
    id: 1,
    name: "Movie App",
    image: require("./images/1.gif"),
    details:
      "React / Axios / Firebase / Toastify / Tailwind-elements / Tailwind-Css",
    giturl: "https://github.com/achieve-software/r32movieapp",
    liveurl: "https://playful-cuchufli-213d17.netlify.app/",
  },

  {
    id: 2,
    name: "NBA Legends",
    image: require("./images/2.gif"),
    details:
      "React / Bootstrap / React-Bootstrap / React-Dom / Basic React Usage   ",
    giturl: "https://github.com/achieve-software/r11nba",
    liveurl: "https://aesthetic-croquembouche-9e333e.netlify.app/",
  },
  {
    id: 3,
    name: "Guess The Number",
    image: require("./images/3.gif"),
    details: "JavaScript / Html / Css / JavaScript Dom Events / Algorithm ",
    giturl: "https://github.com/achieve-software/3guessnumber",
    liveurl: "https://serene-khapse-2e1043.netlify.app/",
  },
  {
    id: 4,
    name: "Checkout Project",
    image: require("./images/4.gif"),
    details: "JavaScript / Html / Css / JavaScript Dom Events / Algorithm ",
    giturl: "https://github.com/achieve-software/40-Checkout-Project",
    liveurl: "https://dashing-syrniki-41189d.netlify.app/",
  },
  {
    id: 5,
    name: "To-Do App",
    image: require("./images/5.gif"),
    details:
      "JavaScript / Html / Css / JavaScript Dom Events / Algorithm / localStorage  ",
    giturl: "https://github.com/achieve-software/39-Todo-App",
    liveurl: "https://subtle-lamington-763dfe.netlify.app/",
  },
  {
    id: 6,
    name: "Tutorial App",
    image: require("./images/6.gif"),
    details:
      "React / Bootstrap / React-Bootstrap / Axios / React İcons / Lifecycle Methods",
    giturl: "https://github.com/achieve-software/r12-tutorial-app",
    liveurl: "https://unique-mooncake-15ad09.netlify.app/",
  },
  {
    id: 7,
    name: "Contact App",
    image: require("./images/7.gif"),
    details: "React / Material UI / MUI İcons / Firebase / React-Toastify /",
    giturl: "https://github.com/achieve-software/r14contactapp",
    liveurl: "https://rainbow-praline-a0873b.netlify.app/",
  },
  {
    id: 8,
    name: "Redux intro",
    image: require("./images/8.gif"),
    details: "React / React-Redux / React-Dom / useDispatch, useSelector Hooks",
    giturl: "https://github.com/achieve-software/r35redux-intro-starter",
    liveurl: "https://preeminent-selkie-771f49.netlify.app/",
  },
  {
    id: 9,
    name: "React To-do App",
    image: require("./images/9.gif"),
    details: "React / React-Dom / Algorithm / Basic React Usage / Basic Css ",
    giturl: "https://github.com/achieve-software/r17reacttodoapp",
    liveurl: "https://voluble-semifreddo-38e869.netlify.app/",
  },
  {
    id: 10,
    name: "React Shop Design",
    image: require("./images/10.gif"),
    details: "React / Bootstrap /  React-Bootstrap / React-Router-Dom ",
    giturl: "https://github.com/achieve-software/r20shopdesign",
    liveurl: "https://sage-bavarois-488d49.netlify.app/",
  },
  {
    id: 11,
    name: "Huddle Project",
    image: require("./images/11.gif"),
    details: "React / Styled-Components /  React-İcons / React-Router-Dom ",
    giturl: "https://github.com/achieve-software/r24huddleprojct",
    liveurl: "https://fanciful-medovik-bc2037.netlify.app/",
  },
  {
    id: 12,
    name: "Hex color",
    image: require("./images/12.gif"),
    details: "React / React-Dom / Javascript / Basic React Usage / Algorithm",
    giturl: "https://github.com/achieve-software/r27hexcolor",
    liveurl: "https://frolicking-syrniki-97eade.netlify.app/",
  },
  {
    id: 13,
    name: "Library",
    image: require("./images/13.gif"),
    details: "React / Styled-Components / Axios /  React-Router-Dom  /",
    giturl: "https://github.com/achieve-software/r28clarus-library-starter",
    liveurl: "https://dapper-baklava-dd51ba.netlify.app/",
  },

  {
    id: 14,
    name: "Google Landing Page",
    image: require("./images/14.gif"),
    details: "Started Html / Css / Basic-Html Usage/ Basic Css Usage",
    giturl: "https://github.com/achieve-software/2googleLand",
    liveurl: "https://stately-boba-9ac91e.netlify.app/",
  },

  {
    id: 15,
    name: "Survey Form",
    image: require("./images/15.gif"),
    details:"Started Html / Css / Basic-Html Usage/ Basic Css Usage",
    giturl: "https://github.com/achieve-software/1shop",
    liveurl: "https://tourmaline-tapioca-5a2336.netlify.app/",
  },
  {
    id: 16,
    name: "Progress Steps",
    image: require("./images/16.gif"),
    details: "JavaScript / Html / Css / JavaScript Dom Events / Algorithm /",
    giturl: "https://github.com/achieve-software/43-Progress-Steps",
    liveurl: "https://marvelous-madeleine-2b56a3.netlify.app/",
  },
  {
    id: 17,
    name: "Color Flipper",
    image: require("./images/17.gif"),
    details: "JavaScript / Html / Css / JavaScript Dom Events / Algorithm /",
    giturl: "https://github.com/achieve-software/42-Color-Flipper",
    liveurl: "https://profound-speculoos-962434.netlify.app/",
  },
  {
    id: 18,
    name: "Appetizer",
    image: require("./images/18.gif"),
    details:  "JavaScript / Html / Css / JavaScript Dom Events / Algorithm /",
    giturl: "https://github.com/achieve-software/41-Appetizer",
    liveurl: "https://polite-fudge-6f1ddb.netlify.app/",
  },
  {
    id: 19,
    name: "IOS Calculator",
    image: require("./images/19.gif"),
    details: "JavaScript / Html / Css / JavaScript Dom Events / Algorithm /",
    giturl: "https://github.com/achieve-software/5IosCalculator",
    liveurl: "https://leafy-heliotrope-83764c.netlify.app/",
  },
  {
    id: 20,
    name: "Web Page Bootstrap",
    image: require("./images/20.gif"),
    details: "Html / Css / Basic-Html Usage / Basic Css Usage / Bootstrap",
    giturl: "https://github.com/achieve-software/7bootstrap",
    liveurl: "https://playful-syrniki-8b0921.netlify.app/",
  },
  {
    id: 21,
    name: "Web Page Bootstrap 2",
    image: require("./images/21.gif"),
    details: "Html / Css / Basic-Html Usage / Basic Css Usage / Bootstrap",
    giturl: "https://github.com/achieve-software/8bootstraplessonproject",
    liveurl: "https://glowing-cucurucho-52cd3f.netlify.app/",
  },
  {
    id: 22,
    name: "Colors Website Sass",
    image: require("./images/22.gif"),
    details:  "Html / Css / Basic-Html Usage / Basic Css Usage / Sass / Scss",
    giturl: "https://github.com/achieve-software/sass",
    liveurl: "https://jovial-swan-b01717.netlify.app/",
  },
  {
    id: 23,
    name: "Web Page Design Sass",
    image: require("./images/23.gif"),
    details: "Html / Css / Basic-Html Usage / Basic Css Usage / Sass / Scss",
    giturl: "https://github.com/achieve-software/6Sass",
    liveurl: "https://fluffy-brigadeiros-21af96.netlify.app/",
  },
  {
    id: 24,
    name: "RGB Color Slider",
    image: require("./images/24.gif"),
    details: "JavaScript / Html / Css / JavaScript Dom Events / Algorithm /",
    giturl: "https://github.com/achieve-software/44-RGB-Color-Slider",
    liveurl: "https://mellow-bubblegum-80a547.netlify.app/",
  },
  {
    id: 25,
    name: "Counter",
    image: require("./images/25.gif"),
    details: "JavaScript / Html / Css / JavaScript Dom Events / Algorithm /",
    giturl: "https://github.com/achieve-software/45-Counter-project",
    liveurl: "https://stellar-croquembouche-9eab8a.netlify.app/",
  },
  {
    id: 26,
    name: "Counter 2",
    image: require("./images/26.gif"),
    details: "JavaScript / Html / Css / JavaScript Dom Events / Algorithm /",
    giturl: "https://github.com/achieve-software/46-Counter-project2",
    liveurl: "https://papaya-sable-f51abe.netlify.app/",
  },
  {
    id: 27,
    name: "Quote",
    image: require("./images/27.gif"),
    details: "React / Basic React Usage / Javascript /  React-Dom  / Algorithm",
    giturl: "https://github.com/achieve-software/r26quoteproject",
    liveurl: "https://resplendent-maamoul-07ef08.netlify.app/",
  },
  {
    id: 28,
    name: "Multiply",
    image: require("./images/28.gif"),
    details: "JavaScript / Html / Css / JavaScript Dom Events / Algorithm / localStorage",
    giturl: "https://github.com/achieve-software/47-mult-app",
    liveurl: "https://marvelous-choux-461585.netlify.app/",
  },
  {
    id: 29,
    name: "Parallax Website",
    image: require("./images/29.gif"),
    details: "Started Html / Css / Basic-Html Usage/ Basic Css Usage",
    giturl: "https://github.com/achieve-software/3parallaxweb",
    liveurl: "https://verdant-churros-24bd00.netlify.app/",
  },
  {
    id: 30,
    name: "Web Site Page Design",
    image: require("./images/30.gif"),
    details: "Started Html / Css / Basic-Html Usage/ Basic Css Usage",
    giturl: "https://github.com/achieve-software/4websitePage",
    liveurl: "https://cosmic-queijadas-ef475f.netlify.app/",
  },
  {
    id: 31,
    name: "React-Sass",
    image: require("./images/31.gif"),
    details: "React / React-Sass / Scss / React-Dom / Basic React Usage",
    giturl: "https://github.com/achieve-software/r5-sass",
    liveurl: "https://jolly-rugelach-187d52.netlify.app/",
  },
  {
    id: 32,
    name: "Appointment",
    image: require("./images/32.gif"),
    details:  "React / Bootstrap /  React-Bootstrap / React-Dom /React İcons",
    giturl: "https://github.com/achieve-software/r16appoinment-project",
    liveurl: "https://courageous-puppy-d0bcc3.netlify.app/",
  },
  {
    id: 33,
    name: "Language Cards",
    image: require("./images/33.gif"),
    details: "React / Basic React Usage /   React-Dom  / JavaScript /Css ",
    giturl: "https://github.com/achieve-software/r8steveproject",
    liveurl: "https://spectacular-crepe-011d00.netlify.app/",
  },
  {
    id: 34,
    name: "Random Number",
    image: require("./images/34.gif"),
    details: "React / Basic React Usage / Javascript /  React-Dom  / Algorithm",
    giturl: "https://github.com/achieve-software/r13randomnum",
    liveurl: "https://cheerful-heliotrope-b7f03a.netlify.app/",
  },
  {
    id: 35,
    name: "İmage Gallery",
    image: require("./images/35.gif"),
    details: "React / Basic React Usage / Javascript /  React-Dom  / Algorithm",
    giturl: "https://github.com/achieve-software/r15imagegallery",
    liveurl: "https://illustrious-parfait-811af3.netlify.app/",
  },
  {
    id: 36,
    name: "Example Router",
    image: require("./images/36.gif"),
    details:  "React / Bootstrap / React-Bootstrap / React-Router-Dom",
    giturl: "https://github.com/achieve-software/r19router-example",
    liveurl: "https://willowy-fox-60c023.netlify.app/",
  },
  {
    id: 37,
    name: "Example Styled Components",
    image: require("./images/37.gif"),
    details:"React / Styled-Components /  React-İcons / React-Dom ",
    giturl: "https://github.com/achieve-software/r23styled-example",
    liveurl: "https://frabjous-rugelach-395e8e.netlify.app/",
  },
  {
    id: 38,
    name: "Recap",
    image: require("./images/38.gif"),
    details:   "React / Bootstrap /  React-Bootstrap / React-Router-Dom /Axios",
    giturl: "https://github.com/achieve-software/r25recapreact",
    liveurl: "https://github.com/achieve-software/r25recapreact",
  },
  {
    id: 39,
    name: "British Meals",
    image: require("./images/39.gif"),
    details:  "React / Basic React Usage / Javascript /  React-Dom  / Algorithm",
    giturl: "https://github.com/achieve-software/r21britshmeals",
    liveurl: "https://venerable-platypus-0a7fb3.netlify.app/",
  },
  {
    id: 40,
    name: "isPalindrome",
    image: require("./images/40.gif"),
    details:"JavaScript / Html / Css / JavaScript Dom Events / Algorithm /",
    giturl: "https://github.com/achieve-software/50-ispalindrome",
    liveurl: "https://gentle-babka-dda712.netlify.app/",
  },
  {
    id: 41,
    name: "Horoscope",
    image: require("./images/41.gif"),
    details: "React / React-Sass / Scss / React-Dom / Basic React Usage",
    giturl: "https://github.com/achieve-software/r6-horoscope",
    liveurl: "https://cerulean-rabanadas-5ac495.netlify.app/",
  },
  {
    id: 42,
    name: "Redux Toolkit",
    image: require("./images/42.gif"),
    details: "React/ Material UI/ Axios/ React Redux / React Router Dom/",
    giturl: "https://github.com/achieve-software/r36redux-toolkit-starter",
    liveurl: "https://glittery-kheer-30c557.netlify.app/",
  },



];
export default PROJECTS;
